apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  serviceAccountName: consul-server-test
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["sleep"]
      args: ["infinity"]
